name: AppFlowy Cloud
description: AppFlowy Cloud
version: 0.9.18
slug: appflowy_cloud
url: "https://github.com/SilvioMessi/hassio-addons/tree/main/appflowy_cloud"
image: ghcr.io/silviomessi/hassio-addons/appflowy_cloud-{arch}
init: false
environment:
  GOTRUE_DB_DRIVER: postgres
  GOTRUE_MAILER_URLPATHS_CONFIRMATION: /gotrue/verify
  GOTRUE_MAILER_URLPATHS_INVITE: /gotrue/verify
  GOTRUE_MAILER_URLPATHS_RECOVERY: /gotrue/verify
  GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: /gotrue/verify
  DATABASE_URL: postgres://supabase_auth_admin:root@localhost:5432/postgres
  PORT: "9999"
  RUST_LOG: info
  APPFLOWY_ENVIRONMENT: production
  APPFLOWY_DATABASE_URL: postgres://postgres:password@localhost:5432/postgres
  APPFLOWY_REDIS_URI: redis://localhost:6379
  APPFLOWY_GOTRUE_JWT_EXP: "7200"
  APPFLOWY_GOTRUE_BASE_URL: http://localhost:9999
  APPFLOWY_S3_USE_MINIO: "true"
  APPFLOWY_S3_MINIO_URL: http://localhost:9000
  APPFLOWY_S3_ACCESS_KEY: minioadmin
  APPFLOWY_S3_SECRET_KEY: minioadmin
  APPFLOWY_S3_BUCKET: appflowy
  APPFLOWY_ACCESS_CONTROL: "true"
  ADMIN_FRONTEND_REDIS_URL: redis://localhost:6379
  ADMIN_FRONTEND_GOTRUE_URL: http://localhost:9999
  ADMIN_FRONTEND_APPFLOWY_CLOUD_URL: http://localhost:8000
  ADMIN_FRONTEND_PATH_PREFIX: /console
  APPFLOWY_INDEXER_ENABLED: "true"
  APPFLOWY_INDEXER_DATABASE_URL: postgres://postgres:password@localhost:5432/postgres
  APPFLOWY_INDEXER_REDIS_URL: redis://localhost:6379
  APPFLOWY_COLLABORATE_MULTI_THREAD: "false"
  APPFLOWY_COLLABORATE_REMOVE_BATCH_SIZE: "100"
  APPFLOWY_WORKER_REDIS_URL: redis://localhost:6379
  APPFLOWY_WORKER_ENVIRONMENT: production
  APPFLOWY_WORKER_DATABASE_URL: postgres://postgres:password@localhost:5432/postgres
  # required by script supabase_auth.sh
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  SUPABASE_PASSWORD: root
options:
  SECRET: change_me
  ADMIN_EMAIL: admin@example.com
  ADMIN_PASSWORD: password
  PUBLIC_URL: http://localhost
  SMTP_HOST: smtp.example.com
  SMTP_PORT: 465
  SMTP_USER: user@example.com
  SMTP_PASSWORD: password
schema:
  SECRET: password
  ADMIN_EMAIL: email
  ADMIN_PASSWORD: password
  PUBLIC_URL: url
  SMTP_HOST: str
  SMTP_PORT: int
  SMTP_USER: email
  SMTP_PASSWORD: password
webui: "http://[HOST]:[PORT:80]"
ports:
  80/tcp: 80
arch:
  - aarch64
  - amd64
