name: AppFlowy Cloud
description: AppFlowy Cloud
version: 0.6.25
slug: appflowy_cloud
url: "https://github.com/SilvioMessi/hassio-addons/tree/main/appflowy_cloud"
image: ghcr.io/silviomessi/hassio-addons/appflowy_cloud-{arch}
init: false
environment:
  API_EXTERNAL_URL: http://localhost
  GOTRUE_DB_DRIVER: postgres
  DATABASE_URL: postgres://supabase_auth_admin:root@localhost:5432/postgres
  GOTRUE_SITE_URL: appflowy-flutter://
  PORT: "9999"
  RUST_LOG: info
  APPFLOWY_ENVIRONMENT: production
  APPFLOWY_DATABASE_URL: postgres://postgres:password@localhost:5432/postgres
  APPFLOWY_REDIS_URI: redis://localhost:6379
  APPFLOWY_GOTRUE_JWT_EXP: "7200"
  APPFLOWY_GOTRUE_BASE_URL: http://localhost:9999
  APPFLOWY_GOTRUE_EXT_URL: http://localhost
  APPFLOWY_S3_USE_MINIO: "true"
  APPFLOWY_S3_MINIO_URL: http://localhost:9000
  APPFLOWY_S3_ACCESS_KEY: minioadmin
  APPFLOWY_S3_SECRET_KEY: minioadmin
  APPFLOWY_S3_BUCKET: appflowy
  APPFLOWY_ACCESS_CONTROL: "true"
  ADMIN_FRONTEND_REDIS_URL: redis://localhost:6379
  ADMIN_FRONTEND_GOTRUE_URL: http://localhost:9999
  ADMIN_FRONTEND_APPFLOWY_CLOUD_URL: http://localhost:8000
  APPFLOWY_GRPC_HISTORY_ADDRS: http://localhost:50051
  APPFLOWY_HISTORY_REDIS_URL: redis://localhost:6379
  APPFLOWY_HISTORY_DATABASE_URL: postgres://postgres:password@localhost:5432/postgres
  APPFLOWY_INDEXER_ENABLED: "true"
  APPFLOWY_INDEXER_DATABASE_URL: postgres://postgres:password@localhost:5432/postgres
  APPFLOWY_INDEXER_REDIS_URL: redis://localhost:6379
  APPFLOWY_COLLABORATE_MULTI_THREAD: "false"
  APPFLOWY_COLLABORATE_REMOVE_BATCH_SIZE: "100"
options:
  SECRET: change_me
  ADMIN_EMAIL: admin@example.com
  ADMIN_PASSWORD: password
schema:
  SECRET: password
  ADMIN_EMAIL: email
  ADMIN_PASSWORD: password
webui: "http://[HOST]:[PORT:80]"
ports:
  80/tcp: 80
arch:
  - aarch64
  - amd64
