name: "Build AppFlowy Cloud"

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: appflowy_cloud
          file: appflowy_cloud/Dockerfile.build
          push: false
          platforms: linux/amd64,linux/arm64