name: "Build AppFlowy Cloud"

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      -
        name: Prepare
        run: |
          platform=${{ matrix.platform }}
          if [ platform="linux/amd64" ]; then
            echo "DOCKER_ARCH=$aarch64" >> $GITHUB_ENV
          else
            echo "DOCKER_ARCH=$amd64" >> $GITHUB_ENV
          fi
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: appflowy_cloud
          file: appflowy_cloud/Dockerfile.build
          push: false
          build-args: BUILD_FROM=ghcr.io/home-assistant/${{ env.DOCKER_ARCH }}-base:3.19
          platforms: ${{ matrix.platform }}