name: Build AppFlowy Cloud container
on: push
permissions:
  contents: read
  packages: write
jobs:
  build-appflowy-cloud-container:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - name: linux-amd64
            runner: ubuntu-latest
            rust_target: x86_64-unknown-linux-musl
            platfom: linux/amd64
            arch: amd64
          - name: linux-arm64
            runner: ubuntu-latest
            rust_target: aarch64-unknown-linux-musl
            platfom: linux/arm64
            arch: aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --target appflowy_cloud \
            --docker-hub ghcr.io/${{ github.repository }} \
            --addon