name: Build AppFlowy Cloud container
on: push
permissions:
  packages: write
jobs:
  build-appflowy-cloud-container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            arch: amd64
          - target: aarch64-unknown-linux-musl
            arch: aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version from config.yml
        id: get-version
        uses: mikefarah/yq@master
        with:
          cmd: yq .version appflowy_cloud/config.yml
      - name: cross-compile-appflowy-cloud-ubuntu
        uses: ./.github/workflows/cross-compile-appflowy-cloud-ubuntu.yml
        with:
          tag: ${{ steps.get-version.outputs.result }}
      - name: Download Appflowy Cloud
        uses: actions/download-artifact@master
        with:
          name: ${{ matrix.target }}-appflowy_cloud-${{ steps.get-version.outputs.result }}
          path: appflowy_cloud/appflowy_cloud
      - name: Download Admin Fronted
        uses: actions/download-artifact@master
        with:
          name: ${{ matrix.target }}-admin_frontend-${{ steps.get-version.outputs.result }}
          path: appflowy_cloud/admin_frontend
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --target appflowy_cloud \
            --docker-hub ghcr.io/${{ github.repository }} \
            --addon
