name: Build AppFlowy Cloud container
on: push
permissions:
  contents: read
  packages: write
jobs:
  build-appflowy-cloud-container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
          - arch: aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --target appflowy_cloud \
            --docker-hub ghcr.io/${{ github.repository }} \
            --build-from ghcr.io/home-assistant/${{ matrix.arch }}-base:latest \
            --addon