name: Build AppFlowy Cloud container
on:
  push:
    branches:
      - main
permissions:
  packages: write
jobs:
  get-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-version.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version from config.yml
        id: get-version
        uses: mikefarah/yq@master
        with:
          cmd: yq .version appflowy_cloud/config.yml
      - name: Check it tag exists
        uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with:
          tag: ${{ steps.get-version.outputs.result }}
      - name: Exit because tag already exists
        run: |
          echo "Tag ${{steps.get-version.outputs.result}} already exists!"
          exit 1
        if: steps.check-tag.outputs.exists == 'true'
  push-tag:
    runs-on: ubuntu-latest
    needs: [get-tag]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="${{needs.get-tag.outputs.tag}}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

