name: (Cross)Compile AppFlowy Cloud with Ubuntu
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "AppFlowy Cloud tag"
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        description: "AppFlowy Cloud tag"
        required: true
        type: string
jobs:
  cross-compile-appflowy-cloud:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
          - target: aarch64-unknown-linux-musl
    steps:
      - name: Checkout AppFlowy Cloud
        uses: actions/checkout@v4
        with:
          repository: AppFlowy-IO/AppFlowy-Cloud
          ref: ${{ inputs.tag }}
      - name: Prepare
        run: |
          sudo apt install -y musl-tools protobuf-compiler
          wget https://musl.cc/aarch64-linux-musl-cross.tgz
          tar -xvzf aarch64-linux-musl-cross.tgz
          mkdir .cargo
          echo [target.aarch64-unknown-linux-musl] >> .cargo/config.toml
          echo 'linker = "./aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc"' >> .cargo/config.toml
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "${{ matrix.target }}"
      - name: Build Appflowy History
        run: |
          sed -i 's/reqwest.workspace = true/reqwest = { workspace = true, features = ["native-tls-vendored"] }/g' libs/app-error/Cargo.toml
          cd services/appflowy-history
          cargo build --verbose --locked --release --bin appflowy_history --target ${{ matrix.target }}
      - name: Upload Appflowy History
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-appflowy-history-${{ inputs.tag }}
          path: target/${{ matrix.target }}/release/appflowy-history
