name: (Cross)Compile AppFlowy Cloud
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "AppFlowy Cloud tag"
        required: true
        type: string
permissions:
  contents: write
jobs:
  cross-compile-appflowy-cloud:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - name: linux-amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: linux-arm64
            runner: ubuntu-latest
            target: aarch64-unknown-linux-gnu
    steps:
      - name: Checkout AppFlowy Cloud
        uses: actions/checkout@v4
        with:
          repository: AppFlowy-IO/AppFlowy-Cloud
          ref: ${{ inputs.tag }}
      - name: Upload Appflowy Cloud
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-appflowy_cloud
          path: Dockerfile
      - name: Upload Admin Fronted
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-admin_frontend
          path: Dockerfile
      - name: Relese Appflowy Cloud
        uses: ncipollo/release-action@v1
        with:
          artifacts: Dockerfile
          allowUpdates: true
          tag: ${{ matrix.target }}-appflowy_cloud-${{ inputs.tag }}
      - name: Relese Admin Fronted
        uses: ncipollo/release-action@v1
        with:
          artifacts: Dockerfile
          allowUpdates: true
          tag: ${{ matrix.target }}-admin_frontend-${{ inputs.tag }}
